### ISSUE TITLE
Why use WMI?

### ISSUE THREAD

**Issue by Lakritzator** [emoacht/DesktopToast#16]
I noticed you are using WMI to query the Windows version, if you don't mind me asking.. why? Does this have an advantage over using the Environment.OSVersion.Version?

I am asking, as I always want to learn better ways. I know, as the developer of Greenshot, that Windows sometimes works in mysterious ways and the most obvious way is not the best.

I currently use Environment.OSVersion.Version, as in the code (which is for the next Greenshot) here: https://github.com/dapplo/Dapplo.Windows/blob/master/src/Dapplo.Windows.Common/WindowsVersion.cs

P.S.
I do know that without having an app.manifest telling Windows that you are "version" aware, you wouldn't get to know it's Windows 10 you are running on.

**Comment by emoacht** [comment]
Hi, Lakritzator,
I preferred WMI for the very reason which you mentioned in the P.S. Environment.OSVersion.Version requires proper declarations in app.manifest. But as far as I know, WMI gives the exact version information regardless of the existence or contents of app.manifest. And since I cannot expect a developer who uses this library always attaches proper app.manifest, I preferred WMI in this case.
I hope this will help.
emoacht

**Comment by Lakritzator** [comment]
This does help, at least to understand why you are using it.

One thing though: the functionality of a lot of system calls still does depend on your manifest. It could be that the way you get the version is telling the truth about the underlying system, your application is still considered unaware of the version and **SOME** of the system calls might still function as if it's running on e.g. Windows 7.... just be aware.

Thanks.
